// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBiqNeq50WO67uq3J_uCFrsy12Hu8HIaGo",
    authDomain: "practicamovil-5711e.firebaseapp.com",
    projectId: "practicamovil-5711e",
    storageBucket: "practicamovil-5711e.appspot.com",
    messagingSenderId: "726321217295",
    appId: "1:726321217295:web:9373eb04dc2df3465ac87a"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2cQb_QsNVNGJyggVynkj9KZUCnYKoSWY',
    appId: '1:205478674110:android:ff89965e08f1c3776668ef',
    messagingSenderId: '205478674110',
    projectId: 'movil-2024-c121b',
    storageBucket: 'movil-2024-c121b.appspot.com',
  );
}
